pipeline {
	agent{label 'master'} 
	stages{
		stage('Fetch repository'){
			steps{
				git url: 'https://github.com/97javilopez/GPI2_lopez.111558.git'
			}
		}
		stage('Simple'){ 
			steps{
				echo 'Compilando carpeta simple'
				dir('simple'){
					sh 'mvn compile'
					sh 'mvn test'
					sh'mvn validate'
					sh'mvn verify'				
				}
			}
		} 
		stage('Android'){ 
			steps{
				echo 'Compilando carpeta Android'
				dir('android-studio'){
					sh './gradlew tasks compileDebugAndroidTestSources'
					sh './gradlew task compileDebugAndroidTestSources'
					sh './gradlew task compileDebugSources'
					sh './gradlew task compileDebugUnitTestSources'
					sh './gradlew task compileReleaseSources'
					sh './gradlew task compileReleaseUnitTestSources'
				}
			}
		} 
		stage('Arduino'){ 
			steps{
				echo 'Compilando carpeta Arduino'
				dir('Arduino-lopez111558'){
					sh 'make'
				}
			}
		} 
		stage('Simple webapp'){ 
			steps{
				echo 'Compilando carpeta Simple Webapp'
				dir('simple-webapp'){
				
				}
			}
		} 
	}
}
